
Running tests... 
----------------------------------------------------------------------
 test_registration (__main__.TestRegistration) ... FAIL (14.854681)s

======================================================================
FAIL [14.854681s]: __main__.TestRegistration.test_registration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:/Users/Alireza/Pictures/Selenium/signup2.py", line 44, in test_registration
    self.fail(f"Registration failed! Screenshot: {screenshot_path}")
AssertionError: Registration failed! Screenshot: reports/screenshots/registration_failed.png

----------------------------------------------------------------------
Ran 1 test in 0:00:17

FAILED
 (Failures=1)

Generating HTML reports... 
reports\Registration_Test_Report___main__.TestRegistration_2025-01-30_16-39-33.html
